[package]
name = "pulsar_ctrl"
version = "0.0.1"
edition = "2024"
rust-version = "1.94"
authors = ["Simon <perso@simontuloup.fr>"]
license = "GPL-3.0-or-later"
description = "Bluetooth receiver and user interface firmware for the ESP32"
publish = false

[[bin]]
name = "pulsar_ctrl"
test = false
bench = false

[dependencies]
esp-idf-svc = "0.52.1"
pulsar_lib = { version = "0.0.1", path = "../pulsar_lib" }

[build-dependencies]
embuild = { version = "0.33.3", features = ["espidf"] }

[profile.release]
codegen-units = 1
opt-level = "s"

[profile.dev]
debug = true
opt-level = 1

[lints.rust]
missing_docs = "deny"
unsafe_code = "deny"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
indexing_slicing = "deny"
unreachable = "deny"
todo = "deny"
unimplemented = "deny"
panic_in_result_fn = "deny"
